// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCl6pJ_7N2Fa7mIgUXq0dgpvxs4JJudYg',
    appId: '1:978138716290:web:e9318a0f4410e290157c9b',
    messagingSenderId: '978138716290',
    projectId: 'mindr-samples-alarm',
    authDomain: 'mindr-samples-alarm.firebaseapp.com',
    storageBucket: 'mindr-samples-alarm.appspot.com',
    measurementId: 'G-F4KR2VS2V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8bMZnfhZiw32TUEDUY3evvUTcjoVlc5A',
    appId: '1:978138716290:android:a6ce969d28687f1d157c9b',
    messagingSenderId: '978138716290',
    projectId: 'mindr-samples-alarm',
    storageBucket: 'mindr-samples-alarm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOHHAjYZsfPQqy7qQaopZNcLWJMp6Re0',
    appId: '1:978138716290:ios:8966fed6742528d6157c9b',
    messagingSenderId: '978138716290',
    projectId: 'mindr-samples-alarm',
    storageBucket: 'mindr-samples-alarm.appspot.com',
    iosClientId: '978138716290-o28e07csme60j4ejj3k1j4e6gv6sc81n.apps.googleusercontent.com',
    iosBundleId: 'com.mindr.alarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOHHAjYZsfPQqy7qQaopZNcLWJMp6Re0',
    appId: '1:978138716290:ios:f877891ba9d4f0c0157c9b',
    messagingSenderId: '978138716290',
    projectId: 'mindr-samples-alarm',
    storageBucket: 'mindr-samples-alarm.appspot.com',
    iosClientId: '978138716290-414jgjuphf6bsgf60gnikqoo17336u2a.apps.googleusercontent.com',
    iosBundleId: 'com.mindr.alarm.RunnerTests',
  );
}
